name: ğŸ§ª Run tests and upload coverage

on: push

permissions:
  contents: read

jobs:
  test:
    name: ğŸ‘¨ğŸ¿â€ğŸ”¬ Run tests and collect coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          fetch-depth: 2
          persist-credentials: false
      - name: Set up Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm run coverage
        continue-on-error: true

      - name: Install dependencies in a subdirectory
        run: npm install
        working-directory: ./packages/cfsite
      - name: Run tests
        run: npm run coverage
        working-directory: ./packages/cfsite
      - name: Upload results to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
